x509_auth/urls.py
# -- code: utf-8 --
from __future__ import absolute_import

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import X509AuthView, X509CreateView, X509ListView, X509DeleteView

urlpatterns = [
    url(r'^auth/$', X509AuthView.as_view(), name='x509_auth_auth'),
    url(r'^map/$',
        login_required(X509CreateView.as_view()),
        name='x509_auth_map'),
    url(r'^list/$',
        login_required(X509ListView.as_view()),
        name='x509_auth_list'),
    url(r'^delete/(?P<pk>\d+)$',
        login_required(X509DeleteView.as_view()),
        name='x509_auth_delete'),
]

x509_auth/models.py
# -- code: utf-8 --
from __future__ import absolute_import

from django.db import models
from django.contrib.auth.models import User


class X509UserMapping(models.Model):
    """ 1:M mapping of Users to certificate (X.509) DNs (subjects) """

    user = models.ForeignKey(
        User,
        verbose_name="User",
        help_text="Django User associated with certificate.",
        default=None, blank=True, null=True,
        related_name="%(app_label)s_%(class)s_related",)

    cert_dn = models.CharField(
        help_text="Certificate matter to match on.",
        max_length=1024,
        blank=False,
        unique=True)

    required = models.BooleanField(
        help_text="This user must authenticate via x509.",
        default=False)

    def __str__(self):
        return "{0}:{1}".format(self.user.username, self.cert_dn)

x509_auth/views.py
# -- code: utf-8 --
from __future__ import absolute_import

import logging

from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy

from .models import X509UserMapping
from .mixins import X509ContextMixin

logger = logging.getLogger(__name__)


class X509AuthView(TemplateView):
    """
    View to look for HTTP headers and if found, map and authenticate a user
    (if possible).
    """

    template_name = "x509_auth/auth.html"

    def get_context_data(self, **kwargs):
        context = super(X509AuthView, self).get_context_data(**kwargs)
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        try:
            dn = request.META['HTTP_X_SSL_USER_DN']
            verified = request.META['HTTP_X_SSL_AUTHENTICATED']
        except KeyError:
            # HTTP headers not set
            messages.error(self.request,
                           'We did not get any certificate information.  '
                           'Please verify that your user certificate to '
                           'loaded in your browser.')
            return self.render_to_response(context)

        # requires our backend
        user = authenticate(dn=dn, verified=verified)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(request.GET.get('next', '/'))
        else:
            for k in ['HTTP_X_SSL_USER_DN', 'HTTP_X_SSL_AUTHENTICATED']:
                context[k] = request.META[k]
            return self.render_to_response(context)


class X509ListView(X509ContextMixin, ListView):
    """
    Lists out certificates owned by request.user.  If there is a certificate
    asserted in the request, and we don't have record of it, offers to add it.
    """

    model = X509UserMapping
    template_name = 'x509_auth/list.html'

    def get_queryset(self):
        """
        Limit query set to logged in user.
        """
        return self.model.objects.filter(user=self.request.user)


class X509CreateView(CreateView):
    """
    Does X509UserMapping creation.  Forces the user attribute to be the
    user that is currently logged in.
    """

    model = X509UserMapping
    template_name = 'x509_auth/create.html'
    fields = ['cert_dn']
    success_url = reverse_lazy('x509_auth_list')

    def form_valid(self, form):
        """
        Force user attribute to be the currently logged in user.
        """
        form.instance.user = self.request.user
        return super(X509CreateView, self).form_valid(form)


class X509DeleteView(DeleteView):
    """
    Performs delete.  User will get a confirmation, and user may only
    delete mappings owned by themselves.
    """

    model = X509UserMapping
    template_name = 'x509_auth/delete.html'
    success_url = reverse_lazy('x509_auth_list')

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(X509DeleteView, self).get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj

x509_auth/templates/x509_auth/auth.html
{% extends "base.html" %}

{% block body %}
<form>
<input type="button" value="Try again" onClick="window.location.reload()">
</form>
{% if HTTP_X_SSL_USER_DN %}
<p>Certificate Subject was {{ HTTP_X_SSL_USER_DN }}</p>
{% endif %}
{% if HTTP_X_SSL_AUTHENTICATED %}
<p>SSL status was {{ HTTP_X_SSL_AUTHENTICATED }}</p>
{% endif %}
{% endblock %}

x509_auth/templates/x509_auth/cert_auth.html
{% extends "base.html" %}

{% block body %}
<form>
<input type="button" value="Try again" onClick="window.location.reload()">
</form>
{% if HTTP_X_SSL_USER_DN %}
<p>Certificate Subject was {{ HTTP_X_SSL_USER_DN }}</p>
{% endif %}
{% if HTTP_X_SSL_AUTHENTICATED %}
<p>SSL status was {{ HTTP_X_SSL_AUTHENTICATED }}</p>
{% endif %}
{% endblock %}

x509_auth/templates/x509_auth/create.html
{% extends "base.html" %}
{% load x509_auth_extras %}
{% block body %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
<!--
{# Exercises template tag #}
{% is_X509_authenticated as authed %}
TEST: {{ authed }}
-->
{% endblock %}

x509_auth/templates/x509_auth/delete.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

x509_auth/templates/x509_auth/list.html
{% extends "base.html" %}
{% load x509_auth_extras %}
{% block body %}
<h1>Certs</h1>
{% if HTTP_X_SSL_AUTHENTICATED %}
You are using this new certificate:
<form action="{% url 'x509_auth_map' %}" method="post">
  {% csrf_token %}
  <p>
    Cert Distinguished Name (DN): <em>{{ HTTP_X_SSL_USER_DN }}</em>
  </p>
  <input id="id_cert_dn" maxlength="1024" name="cert_dn" type="hidden" value="{{ HTTP_X_SSL_USER_DN }}" />
  <input type="submit" value="Add Certificate" />
</form>
{% endif %}
<ul>
{% for mapping in object_list %}
  <li>{{ mapping.user }} - {{ mapping.cert_dn }} <a href="{% url 'x509_auth_delete' pk=mapping.pk %}">Delete</a></li>
{% empty %}
  <li>No X.509 mappings yet.</li>
{% endfor %}
</ul>
{% endblock %}